app:
  host: '0.0.0.0'
  port: 9000
  save_dir: 'save/tmps'
  multithread: True

stt:
  config: 'stt/configs/quartznet12x1_vi.yaml'
  encoder_checkpoint: 'stt/models/acoustic_model/vietnamese/JasperEncoder-STEP-289936.pt'
  decoder_checkpoint: 'stt/models/acoustic_model/vietnamese/JasperDecoderForCTC-STEP-289936.pt'
  lm_path: 'stt/models/language_model/3-gram-lm.binary'
  beam_width: 50
  device: 'gpu'

answer:
  server:
    address: 192.168.50.182
    port: 8080
  openai_key_path: 'save/keys/openai.txt'
  model_name: 'gpt-3.5-turbo'
  temperature: 0.7
  role: 'user'
  max_tokens: 1024
  finish_word: '[DONE]'
  break_word: '[BREAK]'
  retry: 3 # times
  timeout: 2
  statement:
    connection_error: 'Kết nối không ổn định. Vui lòng thử lại sau.[DONE]'

tts:
  language: 'vi'
  slow: False
