app:
  host: '0.0.0.0'
  port: 9000
  save_dir: 'save/tmps'
  multithread: True

answer:
  server:
    address: 10.0.41.67
    port: 8080
  openai_key_path: 'save/keys/openai.txt'
  model_name: 'gpt-3.5-turbo'
  temperature: 0.7
  role: 'user'
  max_tokens: 1024
  finish_word: '[DONE]'
  break_word: '[BREAK]'
  retry: 3 # times
  timeout: 2
  statement:
    connection_error: 'Kết nối không ổn định. Vui lòng thử lại sau.[DONE]'