cam:
  scope:
    x: 85
    y: 45
  device: 0
  grid: 5 # degree
  reset_every: 5 # seconds when not detect faces
model:
  path: 'assets/models/face_detection_yunet_120x160.trt'
infer:
  input_shape: '160,120'
  conf_threshold: 0.9   # Filter low confident bboxes
  nms_threshold: 0.3    # NMS threshold
  top_k: 500            # Keep top_k bboxes before NMS
  keep_top_k: 50        # Keep keep_top_k bboxes after NMS
log:
  state: False          # Log or not
  dir: 'logs'           # logs folder
  every: 10             # seconds
serial:
  port: '/dev/ttyACM0'
  baudrate: 115200
  warmup: 2            # seconds 