system_id: 'bkbot-01'

rabbitmq:
  host: '34.142.132.0'
  user: 'theanh'
  pass: '123456'
  queues:
    log_stats: 'stats'
    log_face_track: 'face_track'

stats:
  dir: log/stats
  every: 10 # seconds
  mem_threshold: 85 # % of memory