server:
  address: '34.142.132.0'
  port: 9000
  api: /answer/stream/stable
  # api: /answer/stream/stable/hust

device:
  mic_index: 11
  sleep_time: 0.2 # seconds

sample:
  greet: 'assets/voices/greet.wav'
  continue: 'assets/voices/continue.wav'
  repeat: 'assets/voices/repeat.wav'
  goodbye: 'assets/voices/goodbye.wav'
  retry: 'assets/voices/retry.wav'
  think: 'assets/voices/think.wav'
  listen_none: 'assets/voices/listen_none.wav'

save: 
  dir: 'assets/tmp'

listen:
  # Energy threshold: higher means lower sensitivity
  # - Quiet room: 0 - 100
  # - Speaking: 150 - 3500
  # - Loud room: up to 4000
  auto_adjust: False # Auto adjust energy threshold
  energy_threshold: 4000
  pause_threshold: 0.8 # Not speaking end (in secs)
  timeout: 10 # Wait for speaking (in secs)

stt:
  lang: 'vi'

answer:
  key: 'assets/openai/key.txt'
  finish_word: '[DONE]'
  break_word: '[BREAK]'

tts:
  lang: 'vi'
  slow: False
  split_char: '. '
  num_sent: 1 # Speak every sentence
  speed: 1.3
  tone: 1

statement:
  exit: "tạm biệt"